In [1]:
import os
import time
import numpy as np

import torch
import torch.nn as nn
import torch.optim as optim
import torch.utils.data as data
import torch.backends.cudnn as cudnn
from tensorboardX import SummaryWriter

import pandas as pd
import scipy.sparse as sp

################################## config.py ###########################
config = {
    "model": "MF",
    "model_path": "./models/",
    "train_rating": "./data/ml-1m.train.rating",
    "train_negative": "./data/ml-1m.train.negative",
    "test_negative": "./data/ml-1m.test.negative",
}

args = {
    "batch_size": 256,
    "dropout": 0.0,
    "epochs": 20,
    "factor_num": 32,
    "gpu": "0",
    "lr": 0.001,
    "num_layers": 3,
    "num_ng": 4,
    "out": True,
    "test_num_ng": 99,
    "top_k": 10,
}
os.environ["CUDA_VISIBLE_DEVICES"] = args["gpu"]
cudnn.benchmark = True


########################## data_utils.py ####################
def load_all():
    """ We load all the three file here to save time in each epoch. """
    train_data = pd.read_csv(
        config["train_rating"],
        sep="\t",
        header=None,
        names=["user", "item"],
        usecols=[0, 1],
        dtype={0: np.int32, 1: np.int32},
    )

    user_num = train_data["user"].max() + 1
    item_num = train_data["item"].max() + 1

    train_data = train_data.values.tolist()

    # dok matrix 형식으로 저장
    train_mat = sp.dok_matrix((user_num, item_num), dtype=np.float32)
    for x in train_data:
        train_mat[x[0], x[1]] = 1.0

    test_data = []
    with open(config["test_negative"], "r") as fd:
        line = fd.readline()
        while line != None and line != "":
            arr = line.split("\t")
            u = eval(arr[0])[0]
            test_data.append([u, eval(arr[0])[1]])
            for i in arr[1:]:
                test_data.append([u, int(i)])
            line = fd.readline()
    return train_data, test_data, user_num, item_num, train_mat


class NCFData(data.Dataset):
    def __init__(self, features, num_item, train_mat=None, num_ng=0, is_training=None):
        super(NCFData, self).__init__()
        """ Note that the labels are only useful when training, we thus 
			add them in the ng_sample() function.
		"""
        self.features_ps = features
        self.num_item = num_item
        self.train_mat = train_mat
        self.num_ng = num_ng
        self.is_training = is_training
        self.labels = [0] * len(features)

    def set_ng_sample(self):
        assert self.is_training, "no need to sampling when testing"

        # negative sample 더하기
        self.features_ng = []
        for x in self.features_ps:
            # user
            u = x[0]
            for _ in range(self.num_ng):
                j = np.random.randint(self.num_item)
                # train set에 있는 경우 다시 뽑기
                while (u, j) in self.train_mat:
                    j = np.random.randint(self.num_item)
                self.features_ng.append([u, j])

        labels_ps = [1] * len(self.features_ps)
        labels_ng = [0] * len(self.features_ng)

        self.features_fill = self.features_ps + self.features_ng
        self.labels_fill = labels_ps + labels_ng

    def __len__(self):
        return (self.num_ng + 1) * len(self.labels)

    def __getitem__(self, idx):
        features = self.features_fill if self.is_training else self.features_ps
        labels = self.labels_fill if self.is_training else self.labels

        user = features[idx][0]
        item = features[idx][1]
        label = labels[idx]
        return user, item, label


############################## PREPARE DATASET ##########################
train_data, test_data, user_num, item_num, train_mat = load_all()


def prepare_data(train_data, test_data, item_num, train_mat):

    # construct the train and test datasets
    # args = (features, num_item, train_mat=None, num_ng=0, is_training=None)
    train_dataset = NCFData(train_data, item_num, train_mat, args["num_ng"], True)
    test_dataset = NCFData(test_data, item_num, train_mat, 0, False)
    train_loader = data.DataLoader(
        train_dataset, batch_size=args["batch_size"], shuffle=True, num_workers=4
    )
    test_loader = data.DataLoader(
        test_dataset, batch_size=args["test_num_ng"] + 1, shuffle=False, num_workers=0
    )

    return train_loader, test_loader


train_loader, test_loader = prepare_data(train_data, test_data, item_num, train_mat)


############################## model.py ###############################


class MF(nn.Module):
    def __init__(
        self, user_num, item_num, factor_num,
    ):
        super(MF, self).__init__()
        self.factor_num = factor_num

        # 임베딩 저장공간 확보; num_embeddings, embedding_dim
        self.embed_user = nn.Embedding(user_num, factor_num)
        self.embed_item = nn.Embedding(item_num, factor_num)
        predict_size = factor_num
        self.predict_layer = torch.ones(predict_size, 1).cuda()
        self._init_weight_()

    def _init_weight_(self):
        # weight 초기화
        nn.init.normal_(self.embed_user.weight, std=0.01)
        nn.init.normal_(self.embed_item.weight, std=0.01)

        # bias 초기화
        for m in self.modules():
            if isinstance(m, nn.Linear) and m.bias is not None:
                m.bias.data.zero_()

    def forward(self, user, item):
        embed_user = self.embed_user(user)
        embed_item = self.embed_item(item)
        output_GMF = embed_user * embed_item
        prediction = torch.matmul(output_GMF, self.predict_layer)
        return prediction.view(-1)


########################### CREATE MODEL #################################


def create_model(user_num, item_num, args):
    model = MF(user_num, item_num, args["factor_num"],)
    model.cuda()
    loss_function = nn.BCEWithLogitsLoss()
    optimizer = optim.Adam(model.parameters(), lr=args["lr"])
    return model, loss_function, optimizer


model, loss_function, optimizer = create_model(user_num, item_num, args)


############################ evaluate.py ###############################


def hit(gt_item, pred_items):
    if gt_item in pred_items:
        return 1
    return 0


def ndcg(gt_item, pred_items):
    if gt_item in pred_items:
        index = pred_items.index(gt_item)
        return np.reciprocal(np.log2(index + 2))
    return 0


def metrics(model, test_loader, top_k):
    HR, NDCG = [], []

    for user, item, _ in test_loader:
        user = user.cuda()
        item = item.cuda()

        predictions = model(user, item)
        # 가장 높은 top_k개 선택
        _, indices = torch.topk(predictions, top_k)
        # 해당 상품 index 선택
        recommends = torch.take(item, indices).cpu().numpy().tolist()
        # 정답값 선택
        gt_item = item[0].item()
        HR.append(hit(gt_item, recommends))
        NDCG.append(ndcg(gt_item, recommends))

    return np.mean(HR), np.mean(NDCG)


########################### TRAINING #####################################

if __name__ == "__main__":
    count, best_hr = 0, 0
    writer = SummaryWriter()  # for visualization
    # 모델 파라미터 출력
    for epoch in range(args["epochs"]):
        model.train()  # Enable dropout (if have).

        start_time = time.time()
        train_loader.dataset.set_ng_sample()

        for user, item, label in train_loader:
            user = user.cuda()
            item = item.cuda()
            label = label.float().cuda()

            # gradient 초기화
            model.zero_grad()
            prediction = model(user, item)
            loss = loss_function(prediction, label)
            loss.backward()
            optimizer.step()
            writer.add_scalar("data/loss", loss.item(), count)
            count += 1

        model.eval()
        HR, NDCG = metrics(model, test_loader, args["top_k"])

        elapsed_time = time.time() - start_time
        print(
            "The time elapse of epoch {:03d}".format(epoch)
            + " is: "
            + time.strftime("%H: %M: %S", time.gmtime(elapsed_time))
        )
        print("HR: {:.3f}\tNDCG: {:.3f}".format(np.mean(HR), np.mean(NDCG)))

        if HR > best_hr:
            best_hr, best_ndcg, best_epoch = HR, NDCG, epoch
            if args["out"]:
                if not os.path.exists(config["model_path"]):
                    os.mkdir(config["model_path"])
                torch.save(
                    model, "{}{}.pth".format(config["model_path"], config["model"])
                )

    print(
        "End. Best epoch {:03d}: HR = {:.3f}, NDCG = {:.3f}".format(
            best_epoch, best_hr, best_ndcg
        )
    )

The time elapse of epoch 000 is: 00: 00: 48
HR: 0.523	NDCG: 0.293
The time elapse of epoch 001 is: 00: 00: 47
HR: 0.599	NDCG: 0.340
The time elapse of epoch 002 is: 00: 00: 48
HR: 0.644	NDCG: 0.374
The time elapse of epoch 003 is: 00: 00: 46
HR: 0.664	NDCG: 0.391
The time elapse of epoch 004 is: 00: 00: 47
HR: 0.682	NDCG: 0.403
The time elapse of epoch 005 is: 00: 00: 47
HR: 0.691	NDCG: 0.411
The time elapse of epoch 006 is: 00: 00: 48
HR: 0.701	NDCG: 0.415
The time elapse of epoch 007 is: 00: 00: 47
HR: 0.695	NDCG: 0.419
The time elapse of epoch 008 is: 00: 00: 48
HR: 0.696	NDCG: 0.419
The time elapse of epoch 009 is: 00: 00: 48
HR: 0.697	NDCG: 0.422
The time elapse of epoch 010 is: 00: 00: 49
HR: 0.700	NDCG: 0.422
The time elapse of epoch 011 is: 00: 00: 48
HR: 0.699	NDCG: 0.421
The time elapse of epoch 012 is: 00: 00: 48
HR: 0.701	NDCG: 0.422
The time elapse of epoch 013 is: 00: 00: 47
HR: 0.702	NDCG: 0.423
The time elapse of epoch 014 is: 00: 00: 46
HR: 0.703	NDCG: 0.421
The time e

In [5]:
user

tensor([ 234, 4516,  668, 1332, 3630, 3402, 5791, 1447, 4084, 4174,  441,   34,
        1391, 4639, 4802, 2795, 3888, 3507, 2097, 4699, 4867, 5993, 2353, 4566,
        1779, 3952, 1050,   52, 4608, 3647, 6029,  658, 1373, 3468,  695, 3149,
        2798, 2453,    8, 2755, 3502, 1448, 4509, 3390,  691, 5625, 2886, 3204,
         201, 3962, 5025, 4185,  659, 1925, 4707, 4063, 2452, 3981,  947, 3772,
        2333,  923, 4519, 2943, 3241,  328, 3840, 1618, 5719, 5779, 4314, 3545,
        5366, 2078, 3823, 4443, 4424, 5697, 1740,  328, 1686, 1864, 2699, 3264,
        3891, 2722, 4115, 1151,  452, 4020, 1424, 1878, 2805], device='cuda:0')

In [6]:
item

tensor([2474,  877,  833, 2685,   48, 3548,  246, 2462, 2990, 2586,  205, 1450,
         693, 1945, 2166,  534, 1090, 1652, 2606, 1480, 1717,  949, 1245, 3162,
        1583, 2384, 1147, 1067, 2020, 1863, 1000, 3579, 3357, 2896, 2731, 2959,
         464, 1663,  111, 2007, 3262,  149, 2601, 2272, 2693,  647, 3443, 1311,
        2860, 2082, 2650, 1926, 1023, 1840,  430, 3600,  107,   27, 1864,  622,
        1797, 1650, 1927, 2864, 1461, 1159,  806,  257,  139,  437,   46, 1804,
        3698, 3333,  949,  512, 2182, 1805,  241,  182, 2599,  955,  297,  659,
        1565, 2309, 2291, 3258, 2540, 3339, 2411, 2871,  517], device='cuda:0')

In [7]:
label

tensor([1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1.], device='cuda:0')